series: GLFW Graphics
title: Textures
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This program demonstrates an implementation for loading a PNG texture.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: GLFW Graphics
    title: Obj Loading
  - series: GLFW Graphics
    title: Point Lighting
